export interface SiteInfo {
  title: string
  description: string
  url: string
  image: string
  twitter: string
}

export const siteInfo: SiteInfo = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  url: 'https://example.com',
  image: 'https://example.com/image.png',
  twitter: '@example',
};
